name: Demo Workflow Success

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "🎉 Workflow GitHub Actions đã chạy thành công!"
